### ISSUE TITLE
Unable to withdraw or stake funds on Ledger Nano S

### ISSUE THREAD

**Issue by muffetman** [bitcat365/auro-wallet-browser-extension#7]
Hello,

Withdrawing or staking funds on Ledger Nano S fails with error "Transaction broadcast failed", which appears after ~3:30min. The Ledger display shows "Signing..." until the timeout occurs then returns back to "Mina is ready". 

The code owner of the Ledger Mina App has stated: "This is probably cased by a timeout on the Auro/Clor.io side due to the increased signing time introduced by the Ledger firmware 2.0.0 upgrade."

Please see here for more details: https://github.com/jspada/ledger-app-mina/issues/18

Clorio has proposed a candidate fix for their wallet, can we get one for Auro as well?

**Comment by muffetman** [comment]
Any feedback on this? Funds are essentially frozen for a lot of Ledger Nano S users..

**Comment by lvshaoping007** [comment]
yes , it fixed in v1.0.9 , you can try this

**Comment by lvshaoping007** [comment]
the fix commit is  24349c20e3a2b5f4ac873561c887b953a9ccc023
